### ISSUE TITLE
Without file of lvis_classes.txt

### ISSUE THREAD

**Issue by xingpingdong** [SysCV/tet#1]
Hi, When I try to test this tracker with pre-trained model. It shows the following errors:

Traceback (most recent call last):
  File "tools/test.py", line 164, in <module>
    main()
  File "tools/test.py", line 111, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/xd1/.local/lib/python3.8/site-packages/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/xd1/.local/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: TaoDataset: [Errno 2] No such file or directory: 'data/lvis/annotations/lvis_classes.txt'

I used the following commands:

CONFIG=configs/tao/tracker_swinL_tao.py
CHECKPOINT=pretrain/teter_tao_swinL_1X_20220807_220424.pth
GPUS=1
PORT=25000
#if [ -z ${PORT} ]; then
#    PORT=33333
#fi

export PYTHONPATH="${PYTHONPATH}:$(dirname $0)/.."

python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \
    tools/test.py $CONFIG $CHECKPOINT --launcher pytorch ${@:5} \
    --eval track --eval-options resfile_path=results/teter_tao_results/

Could you share the file of lvis_classes.txt with me? Or how to generate this file?
Thank you very much

**Comment by siyliepfl** [comment]
Thanks for your question! lvis_classes.txt can be generated from LVIS v0.5 categories. It is a file containing all category's names. I share it here.
[lvis_classes.txt](https://github.com/SysCV/tet/files/10136621/lvis_classes.txt)
